defmodule DeliberateViolation.Violation.Billing.LedgerEntryCaller do
  @moduledoc """
  **DELIBERATE VIOLATION — not compiled by any normal build. See `mix.exs` and the
  README.**

  This is the **call-style** violation, the counterpart to `invoice.ex`'s alias-style
  one: a plain function call, `Module.function()`, from outside
  `DeliberateViolation.Accounting`'s namespace straight at its internal
  `LedgerEntry.create!/1` — real, callable, generated by `LedgerEntry`'s own
  `code_interface` (see sample project 2), and still forbidden from here, because
  `boundary` only ever asks whether the *module* is exported, never how the function
  being called came to exist.
  """

  alias DeliberateViolation.Accounting.LedgerEntry

  def run do
    LedgerEntry.create!(%{description: "Reached in directly", amount: 0})
  end
end
