defmodule ExampleWeb.Endpoint do
  @moduledoc """
  The endpoint, exactly as `mix phx.new` generated it. This includes the dev-only
  `Phoenix.LiveReloader` plug below.

  It is worth knowing why that plug is interesting under a `:strict` boundary, because it is
  the one entry in `ExampleWeb`'s `deps` list that cannot be written unconditionally.
  `:phoenix_live_reload` is an `only: :dev` dependency, so `Phoenix.LiveReloader` exists as a
  module in `:dev` and does not exist in `:test` or `:prod`; a `deps` entry naming a module
  that does not exist in the env currently being compiled is itself an error
  (`unknown boundary Phoenix.LiveReloader is listed as a dependency`).

  The fix is ordinary Elixir, not a boundary concession: the options passed to `use Boundary`
  are an expression evaluated at compile time, and `_build/dev`, `_build/test` and
  `_build/prod` are separate compilations, so the entry is added with
  `if(Mix.env() == :dev, do: [Phoenix.LiveReloader], else: [])`. See `ExampleWeb`. Any
  env-scoped dependency needs the same treatment, for the same reason any other env-specific
  Mix configuration does.
  """

  use Phoenix.Endpoint, otp_app: :example

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_example_key",
    signing_salt: "F4YybzcU",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :example,
    gzip: not code_reloading?,
    only: ExampleWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ExampleWeb.Router
end
