defmodule DeliberateViolation.ViolationTest do
  @moduledoc """
  This example's entire reason to exist is a violation being caught, so — unlike
  examples 1–3, where the caught-violation demo is a README-only walkthrough over a
  scratch file — that has to be more than prose here. This test is the automated proof.

  It shells out to a real, separate `mix compile --warnings-as-errors` invocation
  against `MIX_ENV=violation` (see `mix.exs`: that env alone adds `violation/` to
  `elixirc_paths`, so it is the only build that ever compiles the deliberately-coupled
  `DeliberateViolation.Violation.Billing` domain) and asserts on the real exit code and
  real captured output — not a paraphrase, and not something the reader has to
  reproduce by hand to believe.

  Why a subprocess rather than, say, `Code.compile_file/1` on the violating modules
  directly: `boundary`'s forbidden-reference check is wired in as a Mix *compiler*
  (`compilers: [:boundary] ++ Mix.compilers()`), not a compile-time check inside the
  modules themselves. Only a real `mix compile` run actually invokes it. This mirrors
  `examples/03_decoupling_via_calculation`'s `antipattern/` + `MIX_ENV=antipattern`
  isolation technique (a separate `elixirc_paths` entry gated on env, kept out of every
  normal build) — the difference is that example 3 only ever demonstrates that build
  failing in its README, by hand, because its own point is the decoupling pattern and
  the violation is supporting context. Here the violation *is* the point, so this test
  runs the exact same isolated build as a subprocess and turns "the compiler catches
  it" into something `mix test` (and CI) verifies on every run, the same way every other
  example's `mix test` proves its own point by execution rather than by assertion in a
  README.

  The first run against a fresh checkout compiles this project's dependencies for the
  `:violation` env from scratch (mirroring example 3's own `antipattern` env), which can
  take a minute — hence the generous timeout below.
  """

  use ExUnit.Case, async: false

  @moduletag timeout: :timer.minutes(5)

  test "MIX_ENV=violation mix compile --warnings-as-errors fails, catching both the alias/relationship violation and the call violation" do
    {output, exit_code} =
      System.cmd("mix", ["compile", "--warnings-as-errors"],
        cd: File.cwd!(),
        env: [{"MIX_ENV", "violation"}],
        stderr_to_stdout: true
      )

    assert exit_code == 1,
           "expected `MIX_ENV=violation mix compile --warnings-as-errors` to fail " <>
             "(exit 1) because it compiles a genuine boundary violation, but it exited " <>
             "#{exit_code}. Full output:\n\n#{output}"

    # The alias-style violation: `violation/billing/invoice.ex`'s `belongs_to` names
    # `LedgerEntry` and calls nothing on it — only caught because AshBoundary turns on
    # alias checking for every domain it declares.
    assert output =~ """
           warning: forbidden reference to DeliberateViolation.Accounting.LedgerEntry
             (module DeliberateViolation.Accounting.LedgerEntry is not exported by its owner boundary DeliberateViolation.Accounting)
             violation/billing/invoice.ex:36\
           """

    # The call-style violation: `violation/billing/ledger_entry_caller.ex` calls
    # `LedgerEntry.create!/1` directly — a real function, generated by `LedgerEntry`'s
    # own `code_interface`, and still forbidden because the module itself isn't
    # exported.
    assert output =~ """
           warning: forbidden reference to DeliberateViolation.Accounting.LedgerEntry
             (module DeliberateViolation.Accounting.LedgerEntry is not exported by its owner boundary DeliberateViolation.Accounting)
             violation/billing/ledger_entry_caller.ex:18\
           """
  end

  test "MIX_ENV=violation mix compile (without --warnings-as-errors) still reports both warnings but exits 0" do
    {output, exit_code} =
      System.cmd("mix", ["compile"],
        cd: File.cwd!(),
        env: [{"MIX_ENV", "violation"}],
        stderr_to_stdout: true
      )

    assert exit_code == 0,
           "boundary reports violations as warnings, not hard failures, without " <>
             "--warnings-as-errors — expected exit 0. Full output:\n\n#{output}"

    assert output =~ "forbidden reference to DeliberateViolation.Accounting.LedgerEntry"
  end
end
