import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :example, ExampleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "SLgLK2MHzQAZYHkWAoko46oXliMNeec18bKJWKF+R7hjSc1EGKRN2ME0RUqvVn0L",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch source files and reload the browser on change. `mix phx.new --no-assets` leaves this
# out (there is nothing to bundle), but the `Phoenix.LiveReloader` plug in
# `ExampleWeb.Endpoint` needs patterns to watch to do anything, and this example keeps live
# reload working, not merely present. See `ExampleWeb`'s
# `@dev_only_deps`, which is the boundary-side half of the same story.
config :example, ExampleWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/example_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :example, dev_routes: true

# `Ash.DataLayer.Ets` keeps records in the running node's ETS tables, so a freshly started
# `mix phx.server` has no posts to render. This flag asks `Example.Application` to insert a
# couple through the domain's own code interface on boot, so hitting http://localhost:4000
# shows real data. It is read with `Application.get_env/3` rather than `Mix.env()` at
# runtime, so nothing here depends on Mix being available in a release.
config :example, seed_posts?: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
